/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e2e1',
        'tertiary-container': '#dddcdc',
        'secondary-fixed-dim': '#00daf3',
        'on-tertiary': '#303031',
        'surface-container-lowest': '#0e0e0e',
        'surface-tint': '#00e639',
        'error-container': '#93000a',
        'surface-dim': '#131313',
        'on-primary-fixed': '#002203',
        'surface-container': '#201f1f',
        'on-tertiary-fixed-variant': '#464747',
        'surface-container-highest': '#353534',
        'on-primary-container': '#007117',
        'on-primary': '#003907',
        'surface-variant': '#353534',
        'tertiary-fixed': '#e3e2e2',
        'on-secondary': '#00363d',
        'primary-fixed-dim': '#00e639',
        'error': '#ffb4ab',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'tertiary': '#faf9f8',
        'primary': '#ebffe2',
        'surface': '#131313',
        'on-secondary-fixed': '#001f24',
        'on-surface': '#e5e2e1',
        'background': '#050505',
        'on-tertiary-container': '#606161',
        'tertiary-fixed-dim': '#c7c6c6',
        'primary-fixed': '#72ff70',
        'on-tertiary-fixed': '#1b1c1c',
        'outline-variant': '#3b4b37',
        'on-primary-fixed-variant': '#00530e',
        'on-secondary-container': '#00616d',
        'on-secondary-fixed-variant': '#004f58',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'surface-container-low': '#1c1b1b',
        'primary-container': '#00ff41',
        'on-surface-variant': '#b9ccb2',
        'surface-container-high': '#2a2a2a',
        'secondary': '#bdf4ff',
        'surface-bright': '#3a3939',
        'outline': '#84967e',
        'secondary-container': '#00e3fd',
        'secondary-fixed': '#9cf0ff',
        'inverse-primary': '#006e16',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'Space Grotesk', 'monospace'],
      },
    },
  },
  plugins: [],
};
